#!/usr/bin/env python
from pycoingecko import CoinGeckoAPI

# list of coins https://api.coingecko.com/api/v3/coins/list
price = CoinGeckoAPI().get_price(ids='ethereum', vs_currencies='usd')

# slow down scrolling
print 'step:%d' % (0.09)

print 'colour:grey'
print 'text:ETH ${}'.format(price['ethereum']['usd'])

# set back to default value
print 'step:%d' % (0.05)