#!/usr/bin/env python
from pycoingecko import CoinGeckoAPI

# list of coins https://api.coingecko.com/api/v3/coins/list
price = CoinGeckoAPI().get_price(ids='ethereum', vs_currencies='usd')

print 'step:%d' % (0.09)
print 'colour:grey'
print 'text:ETH ${}'.format(price['ethereum']['usd'])
